definitions:
  model.Movie:
    properties:
      actors:
        type: string
      describe:
        type: string
      directors:
        type: string
      fileLength:
        type: integer
      id:
        type: integer
      languages:
        type: string
      movieName:
        type: string
      nations:
        type: string
      score:
        type: number
      type:
        type: string
    type: object
  model.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
host: 47.98.164.130:8080
info:
  contact:
    name: API Support
  description: gin开发实战接口列表
  license: {}
  title: gin实战
  version: "1.0"
paths:
  /movie/batch/save:
    post:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 批量保存电影基本信息
        in: body
        name: movie
        required: true
        schema:
          $ref: '#/definitions/model.Movie'
          type: object
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 批量保存电影信息
      tags:
      - 电影模块
  /movie/delete/{id}:
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 要删除的电影id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 根据id删除电影信息
      tags:
      - 电影模块
  /movie/query/{id}:
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 电影id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 获取某个电影的信息
      tags:
      - 电影模块
  /movie/save:
    post:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 保存的电影基本信息
        in: body
        name: movie
        required: true
        schema:
          $ref: '#/definitions/model.Movie'
          type: object
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 保存电影信息
      tags:
      - 电影模块
swagger: "2.0"
