definitions:
  model.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact:
    name: API Support
  description: gin开发实战接口列表
  license: {}
  title: gin实战
  version: "1.0"
paths:
  /movie/get/{id}:
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 电影id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 获取某个电影的信息
      tags:
      - 电影模块
swagger: "2.0"
