definitions:
  model.Result:
    properties:
      code:
        example: 0
        type: integer
      data:
        type: object
      message:
        example: 请求信息
        type: string
    type: object
host: localhost:10086
info:
  contact:
    email: lgl050712@163.com
    name: bazinga
    url: https://github.com/BazingaLyn
  description: golang web项目
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: jarvis swagger
  version: "1.0"
paths:
  /batchSaveMovie:
    post:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Result'
      summary: 批量保存电影信息
      tags:
      - 电影
  /movie:
    get:
      consumes:
      - application/x-json-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Result'
      summary: 获取所有的电影
      tags:
      - 电影
  /movie/:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Result'
      summary: 根据电影id获取电影信息
      tags:
      - 电影
  /save/movie:
    post:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Result'
      summary: 保存电影信息
      tags:
      - 电影
  /saveDirector/:
    post:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Result'
      summary: 修改电影信息
      tags:
      - 电影
swagger: "2.0"
